config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'static_pages/about'

  get 'static_pages/help'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<nav class='nav-style'>
  <ul>
    <li><%= link_to 'About', static_pages_about_path %></li>
    <li><%= link_to 'Help', static_pages_help_path %></li>
  </ul>
</nav>


<h1 class='orignal_style'>Luke Helminiak</h1>
<%= image_tag ('luke.jpg'), class:'picture' %>

<p>Find me in app/views/static_pages/home.html.erb</p>

<p> Add 3 personal qualities</p>

<p> First try </p>



<h4> Description</h4>
<div style="color:blue">
  <h2> History </h2>
  <p> Discription of my programming history</p>
</div>